name: CH UMER POS Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Fix Corrupted Gradle Wrapper
        run: |
          rm -f gradle/wrapper/gradle-wrapper.jar
          gradle wrapper
          chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-wrapper-validation-mode: 'warn'

      - name: Clean
        run: ./gradlew clean --no-build-cache --stacktrace

      - name: Run Unit Tests
        run: ./gradlew :app:testDebugUnitTest --no-build-cache --stacktrace

      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-build-cache --stacktrace

      - name: Build Release APK
        run: ./gradlew assembleRelease --no-build-cache --stacktrace

      - name: Build Release AAB
        run: ./gradlew bundleRelease --no-build-cache --stacktrace

      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CH-UMER-POS-Debug-APK
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Release APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CH-UMER-POS-Release-APK
          path: app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Upload Release AAB Bundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CH-UMER-POS-Release-AAB
          path: app/build/outputs/bundle/release/app-release.aab
          
